# Generated by Django 3.1.4 on 2022-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='skypicker_id',
            field=models.CharField(default='123456', max_length=255),
            preserve_default=False,
        ),
    ]
